### ISSUE TITLE
cdk-remote-stack

### ISSUE THREAD

**Issue by pahud** [snese/aga-multiples-regions-exmaple#2]
Hi @snese 

Let's use [cdk-remote-stack](https://github.com/pahud/cdk-remote-stack) library for this. Is it something you'd like to pick up with?

https://github.com/snese/aga-multiples-regions-exmaple/blob/afbf18fd33a5d5fa33127f0671407d7907a50bdc/bin/aga-multiples-regions-exmaple.ts#L24-L27

**Comment by snese** [comment]
Sure, I'll refactor the code with this lib.

**Comment by snese** [comment]
replace the lib.

ref: https://github.com/snese/aga-multiples-regions-exmaple/commit/cebdc0661ab3a30fba6489ba8081dee2c4c0ebd2
